name: Build HA Add-on images (EVopt)

on:
  push:
    branches: [ main ]
    paths:
      - 'evopt/**'
      - 'repository.yaml'
      - '.github/workflows/**'
  pull_request:
    paths:
      - 'evopt/**'
      - 'repository.yaml'
  schedule:
    - cron: '0 14 * * *' 
  workflow_dispatch: {}

concurrency:
  group: evopt-ha-addon-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Lint Home Assistant add-on
        uses: frenck/action-addon-linter@v2
        with:
          path: ./evopt

  build:
    needs: lint
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - arch: amd64
            platform: linux/amd64
          - arch: aarch64
            platform: linux/arm64
    steps:
      # Upstream-SHA holen
      - name: Get latest upstream main commit
        id: get
        uses: actions/github-script@v7
        with:
          script: |
            const r = await github.rest.repos.getBranch({ owner: "andig", repo: "evopt", branch: "main" });
            core.setOutput("sha", r.data.commit.sha);
            core.setOutput("short", r.data.commit.sha.substring(0,7));

      # Repo auschecken (wir ändern config.yaml)
      - uses: actions/checkout@v4

      # Nur bauen, wenn sich Upstream geändert hat
      - name: Detect upstream change
        id: change
        run: |
          PREV_SHA="$(test -f evopt/LAST_UPSTREAM_SHA && cat evopt/LAST_UPSTREAM_SHA || echo '')"
          CUR_SHA='${{ steps.get.outputs.sha }}'
          if [ "$CUR_SHA" = "$PREV_SHA" ]; then
            echo "changed=false" >> $GITHUB_OUTPUT
          else
            echo "changed=true" >> $GITHUB_OUTPUT
          fi

      # SemVer (Patch) berechnen
      - name: Compute SemVer
        id: semver
        if: steps.change.outputs.changed == 'true'
        run: |
          CUR_VER=$(grep -E '^version:' evopt/config.yaml | sed -E 's/version:[[:space:]]*"?(.*)"?/\1/')
          if [[ ! "$CUR_VER" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
            CUR_VER="0.1.0"
          fi
          IFS='.' read -r MA MI PA <<< "$CUR_VER"
          NEXT_VER="$MA.$MI.$((PA+1))"
          echo "next=${NEXT_VER}" >> $GITHUB_OUTPUT

      # Docker login/QEMU/Buildx wie gehabt, aber nur wenn changed==true
      - uses: docker/setup-qemu-action@v3
        if: steps.change.outputs.changed == 'true'
      - uses: docker/setup-buildx-action@v3
        if: steps.change.outputs.changed == 'true'
      - uses: docker/login-action@v3
        if: steps.change.outputs.changed == 'true'
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build & push (${{ matrix.arch }})
        if: steps.change.outputs.changed == 'true'
        uses: docker/build-push-action@v6
        with:
          context: https://github.com/andig/evopt.git#${{ steps.get.outputs.sha }}
          platforms: ${{ matrix.platform }}
          push: true
          tags: |
            docker.io/litithio/${{ matrix.arch }}-evopt-addon:${{ steps.semver.outputs.next }}   # SemVer-Tag
            docker.io/litithio/${{ matrix.arch }}-evopt-addon:main                               # beweglich
          labels: |
            io.hass.type=addon
            io.hass.version=${{ steps.semver.outputs.next }}
            io.hass.arch=${{ matrix.arch }}
            org.opencontainers.image.revision=${{ steps.get.outputs.sha }}

      # version in config.yaml auf neue SemVer setzen + SHA speichern
      - name: Bump version in config.yaml & record SHA
        if: steps.change.outputs.changed == 'true'
        run: |
          sed -i -E 's/^version:.*$/version: "${{ steps.semver.outputs.next }}"/' evopt/config.yaml
          echo '${{ steps.get.outputs.sha }}' > evopt/LAST_UPSTREAM_SHA

      # Commit (mit [skip ci], damit kein Endlosschleifen-Trigger)
      - name: Commit version bump
        if: steps.change.outputs.changed == 'true'
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore(addon): bump to ${{ steps.semver.outputs.next }} [skip ci]"
          file_pattern: |
            evopt/config.yaml
            evopt/LAST_UPSTREAM_SHA
